application: story-track
version: 4
runtime: python
api_version: 1

handlers:
- url: /s/.*
  script: story_line.py
  login: required

- url: /p/.*
  script: story.py
  login: required

- url: /s/migrate_parent
  script: story_line.py
  login: required

- url: /report
  script: report.py
  login: required

- url: /report/.*/.*
  script: report.py
  login: required

- url: /pivotaltracker
  script: pivotaltracker.py

- url: /project
  script: project.py
  login: required

- url: /static
  static_dir : static
